export const DATE_VALUE = new Date(2024, 5, 1);
export const DATE_RESULT = {
  monthNumber: 6,
  monthIndex: 5,
  monthName: 'June',
  shortMonthName: 'Jun',
  year: 2024,
  shortYear: '24',
  allDays: [
    {
      dayNumber: 27,
      fullDayNumber: '27',
      dayName: 'Monday',
      shortDayName: 'Mon',
      dayNumberInWeek: 1,
      monthNumber: 5,
      fullMonthNumber: '05',
      monthIndex: 4,
      monthName: 'May',
      year: 2024,
      timestamp: 1716757200000,
    },
    {
      dayNumber: 28,
      fullDayNumber: '28',
      dayName: 'Tuesday',
      shortDayName: 'Tue',
      dayNumberInWeek: 2,
      monthNumber: 5,
      fullMonthNumber: '05',
      monthIndex: 4,
      monthName: 'May',
      year: 2024,
      timestamp: 1716843600000,
    },
    {
      dayNumber: 29,
      fullDayNumber: '29',
      dayName: 'Wednesday',
      shortDayName: 'Wed',
      dayNumberInWeek: 3,
      monthNumber: 5,
      fullMonthNumber: '05',
      monthIndex: 4,
      monthName: 'May',
      year: 2024,
      timestamp: 1716930000000,
    },
    {
      dayNumber: 30,
      fullDayNumber: '30',
      dayName: 'Thursday',
      shortDayName: 'Thu',
      dayNumberInWeek: 4,
      monthNumber: 5,
      fullMonthNumber: '05',
      monthIndex: 4,
      monthName: 'May',
      year: 2024,
      timestamp: 1717016400000,
    },
    {
      dayNumber: 31,
      fullDayNumber: '31',
      dayName: 'Friday',
      shortDayName: 'Fri',
      dayNumberInWeek: 5,
      monthNumber: 5,
      fullMonthNumber: '05',
      monthIndex: 4,
      monthName: 'May',
      year: 2024,
      timestamp: 1717102800000,
    },
    {
      dayNumber: 1,
      fullDayNumber: '01',
      dayName: 'Saturday',
      shortDayName: 'Sat',
      dayNumberInWeek: 6,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1717189200000,
    },
    {
      dayNumber: 2,
      fullDayNumber: '02',
      dayName: 'Sunday',
      shortDayName: 'Sun',
      dayNumberInWeek: 7,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1717275600000,
    },
    {
      dayNumber: 3,
      fullDayNumber: '03',
      dayName: 'Monday',
      shortDayName: 'Mon',
      dayNumberInWeek: 1,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1717362000000,
    },
    {
      dayNumber: 4,
      fullDayNumber: '04',
      dayName: 'Tuesday',
      shortDayName: 'Tue',
      dayNumberInWeek: 2,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1717448400000,
    },
    {
      dayNumber: 5,
      fullDayNumber: '05',
      dayName: 'Wednesday',
      shortDayName: 'Wed',
      dayNumberInWeek: 3,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1717534800000,
    },
    {
      dayNumber: 6,
      fullDayNumber: '06',
      dayName: 'Thursday',
      shortDayName: 'Thu',
      dayNumberInWeek: 4,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1717621200000,
    },
    {
      dayNumber: 7,
      fullDayNumber: '07',
      dayName: 'Friday',
      shortDayName: 'Fri',
      dayNumberInWeek: 5,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1717707600000,
    },
    {
      dayNumber: 8,
      fullDayNumber: '08',
      dayName: 'Saturday',
      shortDayName: 'Sat',
      dayNumberInWeek: 6,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1717794000000,
    },
    {
      dayNumber: 9,
      fullDayNumber: '09',
      dayName: 'Sunday',
      shortDayName: 'Sun',
      dayNumberInWeek: 7,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1717880400000,
    },
    {
      dayNumber: 10,
      fullDayNumber: '10',
      dayName: 'Monday',
      shortDayName: 'Mon',
      dayNumberInWeek: 1,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1717966800000,
    },
    {
      dayNumber: 11,
      fullDayNumber: '11',
      dayName: 'Tuesday',
      shortDayName: 'Tue',
      dayNumberInWeek: 2,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1718053200000,
    },
    {
      dayNumber: 12,
      fullDayNumber: '12',
      dayName: 'Wednesday',
      shortDayName: 'Wed',
      dayNumberInWeek: 3,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1718139600000,
    },
    {
      dayNumber: 13,
      fullDayNumber: '13',
      dayName: 'Thursday',
      shortDayName: 'Thu',
      dayNumberInWeek: 4,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1718226000000,
    },
    {
      dayNumber: 14,
      fullDayNumber: '14',
      dayName: 'Friday',
      shortDayName: 'Fri',
      dayNumberInWeek: 5,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1718312400000,
    },
    {
      dayNumber: 15,
      fullDayNumber: '15',
      dayName: 'Saturday',
      shortDayName: 'Sat',
      dayNumberInWeek: 6,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1718398800000,
    },
    {
      dayNumber: 16,
      fullDayNumber: '16',
      dayName: 'Sunday',
      shortDayName: 'Sun',
      dayNumberInWeek: 7,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1718485200000,
    },
    {
      dayNumber: 17,
      fullDayNumber: '17',
      dayName: 'Monday',
      shortDayName: 'Mon',
      dayNumberInWeek: 1,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1718571600000,
    },
    {
      dayNumber: 18,
      fullDayNumber: '18',
      dayName: 'Tuesday',
      shortDayName: 'Tue',
      dayNumberInWeek: 2,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1718658000000,
    },
    {
      dayNumber: 19,
      fullDayNumber: '19',
      dayName: 'Wednesday',
      shortDayName: 'Wed',
      dayNumberInWeek: 3,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1718744400000,
    },
    {
      dayNumber: 20,
      fullDayNumber: '20',
      dayName: 'Thursday',
      shortDayName: 'Thu',
      dayNumberInWeek: 4,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1718830800000,
    },
    {
      dayNumber: 21,
      fullDayNumber: '21',
      dayName: 'Friday',
      shortDayName: 'Fri',
      dayNumberInWeek: 5,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1718917200000,
    },
    {
      dayNumber: 22,
      fullDayNumber: '22',
      dayName: 'Saturday',
      shortDayName: 'Sat',
      dayNumberInWeek: 6,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1719003600000,
    },
    {
      dayNumber: 23,
      fullDayNumber: '23',
      dayName: 'Sunday',
      shortDayName: 'Sun',
      dayNumberInWeek: 7,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1719090000000,
    },
    {
      dayNumber: 24,
      fullDayNumber: '24',
      dayName: 'Monday',
      shortDayName: 'Mon',
      dayNumberInWeek: 1,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1719176400000,
    },
    {
      dayNumber: 25,
      fullDayNumber: '25',
      dayName: 'Tuesday',
      shortDayName: 'Tue',
      dayNumberInWeek: 2,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1719262800000,
    },
    {
      dayNumber: 26,
      fullDayNumber: '26',
      dayName: 'Wednesday',
      shortDayName: 'Wed',
      dayNumberInWeek: 3,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1719349200000,
    },
    {
      dayNumber: 27,
      fullDayNumber: '27',
      dayName: 'Thursday',
      shortDayName: 'Thu',
      dayNumberInWeek: 4,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1719435600000,
    },
    {
      dayNumber: 28,
      fullDayNumber: '28',
      dayName: 'Friday',
      shortDayName: 'Fri',
      dayNumberInWeek: 5,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1719522000000,
    },
    {
      dayNumber: 29,
      fullDayNumber: '29',
      dayName: 'Saturday',
      shortDayName: 'Sat',
      dayNumberInWeek: 6,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1719608400000,
    },
    {
      dayNumber: 30,
      fullDayNumber: '30',
      dayName: 'Sunday',
      shortDayName: 'Sun',
      dayNumberInWeek: 7,
      monthNumber: 6,
      fullMonthNumber: '06',
      monthIndex: 5,
      monthName: 'June',
      year: 2024,
      timestamp: 1719694800000,
    },
  ],
};
